# Generated by Django 2.0.7 on 2022-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='First Name')),
                ('last_name', models.TextField(default='Last Name')),
                ('age', models.SmallIntegerField()),
                ('profile_picture', models.ImageField(default='/Users/shaun/Projects/blinders/src/profile_picture.jpeg', upload_to='')),
                ('blurred_profile_picture', models.ImageField(default='/Users/shaun/Projects/blinders/src/profile_picture.jpeg', upload_to='')),
                ('description', models.TextField(default='Description')),
                ('summary', models.TextField(default='Summary')),
            ],
        ),
    ]
