# Generated by Django 4.1.2 on 2022-10-10 10:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.BooleanField(default=False)),
                ('date_liked', models.DateField(auto_now=True)),
                ('date_confirmed', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NONBINARY', 'Nonbinary')], max_length=10, null=True)),
                ('match_distance', models.IntegerField(default=30)),
                ('match_age_max', models.IntegerField(default=99)),
                ('match_age_min', models.IntegerField(default=18)),
                ('match_gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('ALL', 'All')], max_length=10, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('bio', models.TextField(default='Add a bio', max_length=5000, null=True)),
                ('profile_picture_url', models.ImageField(blank=True, default='media/images/default_profile_picture.jpg', upload_to='images/')),
                ('blurred_profile_picture_url', models.ImageField(blank=True, default='media/images/default_profile_picture.jpg', upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blinders.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='likee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likee', to='blinders.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='blinders.profile'),
        ),
    ]
