# Generated by Django 4.1.2 on 2022-10-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
