# Generated by Django 4.1.2 on 2022-10-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_liked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
