# Generated by Django 4.1.2 on 2022-10-06 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='match_age_max',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='profile',
            name='match_age_min',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='match_distance',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
