# Generated by Django 4.1.2 on 2022-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0002_profile_match_age_max_profile_match_age_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('PENDING', 'Pending'), ('NONBINARY', 'Nonbinary')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='match_gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('PENDING', 'Pending'), ('NONBINARY', 'Nonbinary')], default='PENDING', max_length=10),
        ),
    ]
