# Generated by Django 4.1.2 on 2022-10-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0002_profile_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='display_name',
        ),
    ]
