# Generated by Django 4.1.2 on 2022-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0003_profile_gender_profile_match_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NONBINARY', 'Nonbinary')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='match_gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NONBINARY', 'Nonbinary')], max_length=10, null=True),
        ),
    ]
