# Generated by Django 4.1.2 on 2022-10-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0003_rename_first_name_profile_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='first_name',
        ),
    ]
