# Generated by Django 4.1.2 on 2022-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0003_remove_user_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blurred_profile_picture',
            field=models.ImageField(default='/Users/shaun/Projects/blinders/src/profile_picture.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='/Users/shaun/Projects/blinders/src/profile_picture.jpeg', upload_to='images/'),
        ),
    ]
