# Generated by Django 4.1.2 on 2022-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0005_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blurred_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
