# Generated by Django 4.1.2 on 2022-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0005_rename_matchee_id_match_likee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date_liked',
            field=models.DateField(auto_now=True),
        ),
    ]
