# Generated by Django 4.1.2 on 2022-10-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0006_alter_user_blurred_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
