# Generated by Django 4.1.2 on 2022-10-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinders', '0007_rename_profile_pic_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blurred_profile_picture',
            new_name='blurred_profile_picture_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='profile_picture_url',
        ),
    ]
