# Generated by Django 4.1 on 2022-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurrer_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blurred_profile_picture',
            field=models.ImageField(default='/Users/shaun/Projects/blinders/src/profile_picture.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/Users/shaun/Projects/blinders/src/profile_picture.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.TextField(default='Summary'),
        ),
    ]
